/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as PoliticalContestationRouteImport } from './routes/political-contestation'
import { Route as PartyPrimaryRouteImport } from './routes/party-primary'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MajorityRouteImport } from './routes/majority'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPtrSplatRouteImport } from './routes/api/ptr.$'

const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticalContestationRoute = PoliticalContestationRouteImport.update({
  id: '/political-contestation',
  path: '/political-contestation',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPrimaryRoute = PartyPrimaryRouteImport.update({
  id: '/party-primary',
  path: '/party-primary',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorityRoute = MajorityRouteImport.update({
  id: '/majority',
  path: '/majority',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtrSplatRoute = ApiPtrSplatRouteImport.update({
  id: '/api/ptr/$',
  path: '/api/ptr/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/party-primary': typeof PartyPrimaryRoute
  '/political-contestation': typeof PoliticalContestationRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/party-primary': typeof PartyPrimaryRoute
  '/political-contestation': typeof PoliticalContestationRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/party-primary': typeof PartyPrimaryRoute
  '/political-contestation': typeof PoliticalContestationRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/majority'
    | '/members'
    | '/party-primary'
    | '/political-contestation'
    | '/polls'
    | '/api/ptr/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/majority'
    | '/members'
    | '/party-primary'
    | '/political-contestation'
    | '/polls'
    | '/api/ptr/$'
  id:
    | '__root__'
    | '/'
    | '/majority'
    | '/members'
    | '/party-primary'
    | '/political-contestation'
    | '/polls'
    | '/api/ptr/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MajorityRoute: typeof MajorityRoute
  MembersRoute: typeof MembersRoute
  PartyPrimaryRoute: typeof PartyPrimaryRoute
  PoliticalContestationRoute: typeof PoliticalContestationRoute
  PollsRoute: typeof PollsRoute
  ApiPtrSplatRoute: typeof ApiPtrSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/political-contestation': {
      id: '/political-contestation'
      path: '/political-contestation'
      fullPath: '/political-contestation'
      preLoaderRoute: typeof PoliticalContestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party-primary': {
      id: '/party-primary'
      path: '/party-primary'
      fullPath: '/party-primary'
      preLoaderRoute: typeof PartyPrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majority': {
      id: '/majority'
      path: '/majority'
      fullPath: '/majority'
      preLoaderRoute: typeof MajorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptr/$': {
      id: '/api/ptr/$'
      path: '/api/ptr/$'
      fullPath: '/api/ptr/$'
      preLoaderRoute: typeof ApiPtrSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MajorityRoute: MajorityRoute,
  MembersRoute: MembersRoute,
  PartyPrimaryRoute: PartyPrimaryRoute,
  PoliticalContestationRoute: PoliticalContestationRoute,
  PollsRoute: PollsRoute,
  ApiPtrSplatRoute: ApiPtrSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
