/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MajorityRouteImport } from './routes/majority'
import { Route as ApiPtrSplatRouteImport } from './routes/api/ptr.$'

const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorityRoute = MajorityRouteImport.update({
  id: '/majority',
  path: '/majority',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtrSplatRoute = ApiPtrSplatRouteImport.update({
  id: '/api/ptr/$',
  path: '/api/ptr/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRoutesByTo {
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/majority': typeof MajorityRoute
  '/members': typeof MembersRoute
  '/polls': typeof PollsRoute
  '/api/ptr/$': typeof ApiPtrSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/majority' | '/members' | '/polls' | '/api/ptr/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/majority' | '/members' | '/polls' | '/api/ptr/$'
  id: '__root__' | '/majority' | '/members' | '/polls' | '/api/ptr/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MajorityRoute: typeof MajorityRoute
  MembersRoute: typeof MembersRoute
  PollsRoute: typeof PollsRoute
  ApiPtrSplatRoute: typeof ApiPtrSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/majority': {
      id: '/majority'
      path: '/majority'
      fullPath: '/majority'
      preLoaderRoute: typeof MajorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ptr/$': {
      id: '/api/ptr/$'
      path: '/api/ptr/$'
      fullPath: '/api/ptr/$'
      preLoaderRoute: typeof ApiPtrSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MajorityRoute: MajorityRoute,
  MembersRoute: MembersRoute,
  PollsRoute: PollsRoute,
  ApiPtrSplatRoute: ApiPtrSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
