name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build app
        env:
          VITE_UPSTREAM_API_URL: ${{ secrets.VITE_UPSTREAM_API_URL }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_DISCORD_REDIRECT_TO: ${{ secrets.VITE_DISCORD_REDIRECT_TO }}
          VITE_DISCORD_LOGIN_ENABLED: ${{ secrets.VITE_DISCORD_LOGIN_ENABLED }}
        run: npm run build

      - name: Fix asset path separator
        run: sed -i 's/\.\.\\\\public/..\/public/' .output/server/wrangler.json
        working-directory: .

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            workingDirectory: .output/server
            wranglerVersion: "4"
            command: deploy index.mjs --config wrangler.json